# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- azure-pipelines

jobs:
- job: Build
  timeoutInMinutes: 0

  variables:
    - group: che-theia
    - name: organization
      value: camino
    - name: tag
      value: next

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
      cd dockerfiles/theia-dev
      ./build.sh --build-arg:GITHUB_TOKEN=$(github_token) --organization:$(organization) --tag:$(tag)
    displayName: Building theia-dev

  - script: |
      export
      cd dockerfiles/theia
      ./build.sh --build-args:GITHUB_TOKEN=$(github_token),THEIA_VERSION=master --tag:$(tag) --branch:master --git-ref:refs\\/heads\\/master --organization:$(organization)
    displayName: Building Theia

  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      dockerRegistryEndpoint: camino.azurecr.io
      containerRegistryType: Container Registry
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - script: |
      docker tag $(organization)/che-theia-dev:$(tag) camino.azurecr.io/$(organization)/che-theia-dev:$(tag)
      docker tag $(organization)/che-theia:$(tag) camino.azurecr.io/$(organization)/che-theia:$(tag)
      docker push camino.azurecr.io/$(organization)/che-theia-dev:$(tag)
      docker push camino.azurecr.io/$(organization)/che-theia:$(tag)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: Pushing
