# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- azure-pipelines

jobs:
- job: Build
  timeoutInMinutes: 0

  variables:
    - group: che-theia
    - name: organization
      value: camino
    - name: prefix
      value: che
    - name: tag
      value: next

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.18.2'

  - script: yarn
    displayName: Run yarn.

  - script: |
      cd dockerfiles/theia-dev
      ./build.sh --build-arg:GITHUB_TOKEN=${GITHUB_TOKEN} --organization:$(organization) --tag:$(tag) --prefix:$(prefix)
    displayName: Building theia-dev
    env:
      GITHUB_TOKEN: $(github_token)

  - script: |
      cd dockerfiles/theia
      ./build.sh --build-args:GITHUB_TOKEN=${GITHUB_TOKEN} --tag:$(tag) --prefix:$(prefix) --organization:$(organization) --dockerfile:Dockerfile.alpine
    displayName: Building Theia
    env:
      GITHUB_TOKEN: $(github_token)

  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      dockerRegistryEndpoint: camino.azurecr.io
      containerRegistryType: Container Registry

  - script: |
      docker tag $(organization)/che-theia-dev:$(tag) camino.azurecr.io/$(organization)/che-theia-dev:$(tag)
      docker tag $(organization)/che-theia:$(tag) camino.azurecr.io/$(organization)/che-theia:$(tag)
      docker push camino.azurecr.io/$(organization)/che-theia-dev:$(tag)
      docker push camino.azurecr.io/$(organization)/che-theia:$(tag)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: Pushing

  - script: |
      docker tag $(organization)/che-theia-dev:$(tag) camino.azurecr.io/$(organization)/che-theia-dev:$(tag)-pr$(System.PullRequest.PullRequestNumber)
      docker tag $(organization)/che-theia:$(tag) camino.azurecr.io/$(organization)/che-theia:$(tag)-pr$(System.PullRequest.PullRequestNumber)
      docker push camino.azurecr.io/$(organization)/che-theia-dev:$(tag)-pr$(System.PullRequest.PullRequestNumber)
      docker push camino.azurecr.io/$(organization)/che-theia:$(tag)-pr$(System.PullRequest.PullRequestNumber)
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    displayName: Pushing (staging)
